### ISSUE TITLE
Corpses + Clothing blood not working

### ISSUE THREAD

**Issue by LuigiBoi** [Crystalwarrior/Script_Blood#2]
Blood will never get on the player when attacked and corpses will not spawn.

**Comment by Crystalwarrior** [comment]
This only includes the blood package. If you want the blood to get on player get https://github.com/Crystalwarrior/Player_MeleeAnims and use it as a playertype.

**Comment by LuigiBoi** [comment]
What about corpses, or is that a seperate addon?

**Comment by Crystalwarrior** [comment]
Separate
